/** @format */

import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import { getProviders, getSession, useSession, signOut } from "next-auth/react";
import Modal from "../components/Modal";
import Widgets from "../components/Widets";
export default function Home({ trendingResults, followResults }) {
  const { data: session } = useSession();
  console.log(session);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black min-h-screen max-w-[1500px] mx-auto flex">
        <Sidebar />
        <Feed />
        <Widgets
          trendingResults={trendingResults}
          followResults={followResults}
        />
        {/* <Modal /> */}
      </main>
      <Modal />
    </div>
  );
}

export async function getServerSideProps(context) {
  const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );

  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/login",
      },
    };
  }

  return {
    props: {
      trendingResults,
      followResults,
      session,
    },
  };
}
